# Spring properties
spring.application.name=game-service

spring.datasource.url=jdbc:postgresql://localhost:5432/game
spring.datasource.username=postgres
spring.datasource.password=mine

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true

#Она работает так: при каждом запуске приложения Hibernate сканирует классы с аннотацией @Entity,
# сверяет их с реальными таблицами в PostgreSQL и,
# если таблицы нет (или её структура изменилась), автоматически создаёт её в базе
spring.jpa.hibernate.ddl-auto=update

# Активация пакетной записи (JDBC Batching)
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true


# Указываем, что используем именно caffeine
spring.cache.type=caffeine
spring.cache.cache-names=best_result,games,player_stats
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=5m


error.path=/error

# HTTP Server
server.port=2222

eureka.client.serviceUrl.defaultZone=http://localhost:1111/eureka/
eureka.client.instance.leaseRenewalIntervalInSeconds=5

management.endpoints.web.exposure.include=*

spring.threads.virtual.enabled=true

# Увеличиваем пул соединений, так как Лумы позволяют держать больше параллельных задач
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10

grpc.server.port=6566
eureka.instance.metadata-map.grpc.port=${grpc.server.port}


